from html import escape as e

def about(name,kind):
 purpose={'atlas':'A closer look at the names, origins, formats, and stories behind California cannabis. Our starting point is San Jose; a California label does not automatically mean a Bay Area-grown product.','terpenes':'A sensory vocabulary for curious adults. Nose Notes connects familiar aroma words with chemical references, source records, and a transparent lab-report converter.','delivery':'A San Jose guide to understanding delivery information: the difference between registration and service coverage, the line items on a receipt, and the details a provider must explain.'}[kind]
 return f'''<section class="section"><div class="wrap article"><p class="eyebrow">THE PROJECT</p><h2>Curiosity deserves useful answers.</h2><p>{purpose}</p><p>{name} is a sponsored educational publication for adults 21+. It is not a dispensary, a medical service, an independent testing laboratory, or a government directory. We do not claim to have visited, purchased from, or personally tested every business or product mentioned.</p><h2>What earns a place here</h2><p>Explanations should answer a real question. Factual descriptions should have a traceable source. Tools should show their assumptions. Local context should identify real San Jose places without implying that a venue endorses cannabis use or this publication.</p><h2>Who supports the work</h2><p>Purple Lotus is the current sponsor. That relationship is disclosed at the top of every page. The sponsorship programme is open to relevant organizations under the same published standards. A sponsorship is a labeled commercial relationship, not evidence that a business has been independently rated or recommended.</p><h2>How the content is produced</h2><p>The publication uses public-source research, automated data checks, and editorial synthesis. Source dates and editorial dates are kept separate. Local photographs have documented origins and licenses.</p><h2>What readers can verify</h2><p>Use the source links to check factual claims, consult the methodology to understand calculations, and review the sponsorship policy to see how placements are labeled.</p><div class="policy-links"><a href="team.html">Meet the editorial voices ↗</a><a href="editorial-standards.html">Editorial standards ↗</a><a href="advertise.html">Sponsorship opportunities ↗</a></div></div></section>'''

def team(name):
 return ''

def standards():
 return '''<section class="section"><div class="wrap article"><h2>Sources before certainty.</h2><p>Use official company references for a company’s own descriptions, public agencies for regulatory records, and identified scientific records for chemical facts. A company statement is attributed, not converted into an independent endorsement. Dates refer to the specific material checked.</p><h2>Clear limits on experience.</h2><p>We do not describe desk research as a visit, interview, product test, or firsthand review. Generated illustrative art is not evidence of a real product, place, event, or staff member.</p><h2>Sponsorship and editorial treatment.</h2><p>Paid or supported placements are labeled. The same evidence requirements apply to a sponsor and a non-sponsor. Sponsorship does not purchase a favorable rating, removal of a relevant correction, a fabricated testimonial, or an undisclosed recommendation. Directories state their selection limits and are not presented as exhaustive rankings.</p><h2>Calculations and data freshness.</h2><p>Tools explain their inputs and avoid filling unknown values with invented facts. Fetched data and editorial judgments are separate. If an automated check fails, the last valid values keep their original dates and a review flag should remain visible. A fetch date does not prove every sentence was independently re-reviewed.</p><h2>Corrections.</h2><p>A correction should identify the page, the specific claim, and a reliable source. Confirmed factual changes should be recorded with the date and reason. Publisher contact details can be added when the publication opens its public inquiry channel. This page does not claim that a submitted message was received.</p><h2>Health and consumer information.</h2><p>Aroma descriptors do not predict an individual’s response to cannabis. This publication does not diagnose, prescribe, provide legal advice, or replace original regulatory records. Provider references do not establish current availability at a particular address.</p><h2>Change record</h2><p><strong>September 23, 2026:</strong> Added the sponsorship policy, publishing process, and expanded editorial standards. STAY IN’s main tools were changed to use reader-entered assumptions rather than one sponsor’s commercial terms.</p></div></section>'''

def advertise(name,email=''):
 email=e(email,quote=True)
 return f'''<section class="section"><div class="wrap"><div class="advertise-lead"><div><p class="eyebrow">ADVERTISE & SUPPORT</p><h2>Help useful<br>information travel.</h2><p>Reach curious adult readers through clearly labeled support for {name}. Local businesses, cultural organizations, and relevant brands may propose a partnership under the same editorial rules.</p><p>Placement availability, pricing, and audience information are discussed before an engagement.</p></div><div class="support-box"><p class="eyebrow">CURRENT SUPPORTER</p><h3>Purple Lotus</h3><p>A labeled placement for the current publication sponsor.</p><a href="editorial-standards.html">Read the sponsorship policy ↗</a></div></div><div class="support-options"><article><span>01</span><h3>Publication supporter</h3><p>A clearly identified sponsor credit that helps keep the educational resource accessible.</p></article><article><span>02</span><h3>Tool supporter</h3><p>Support a useful calculator or reference feature, with acknowledgment beside the tool and no influence over its math.</p></article><article><span>03</span><h3>Labeled partner feature</h3><p>A separately labeled commercial feature, subject to factual review and kept distinct from editorial guides.</p></article></div><div class="inquiry-layout"><div><h2>Start with a clear brief.</h2><p>Prepare a sponsorship inquiry to save or share. This form creates a document in your browser. It does not submit a message or reserve a placement.</p>{('<p><a href="mailto:'+email+'">Email the publisher ↗</a></p>') if email else '<p class="small">Direct email inquiries are not open on this preview. A public publisher contact will be added before the programme opens.</p>'}<a href="assets/sponsorship-kit.txt" download>Download the sponsorship overview ↗</a></div><form id="sponsor-brief"><label>Organization<input name="organization" required maxlength="100"></label><label>Your public website<input name="website" type="url" placeholder="https://" maxlength="200"></label><label>What would you like to support?<select name="placement"><option>Publication supporter</option><option>Tool supporter</option><option>Labeled partner feature</option></select></label><label>Your idea<textarea name="idea" rows="4" required maxlength="2000"></textarea></label><button class="btn dark" type="submit">Download inquiry brief</button><p id="brief-status" class="small" aria-live="polite"></p></form></div></div></section>'''

def homepage_about(name):
 return f'''<section class="section project-about"><div class="wrap"><div><p class="eyebrow">ABOUT {name}</p><h2>More to say.<br>More to discover.</h2><p>Stories, useful tools, and a point of view on San Jose. Meet the writers and explore the journal.</p></div><div class="about-links"><a href="about.html">About the publication <span>↗</span></a><a href="team.html">Our writers <span>↗</span></a><a href="editorial-standards.html">Our standards <span>↗</span></a><a href="advertise.html">Advertise & support <span>↗</span></a></div></div></section>'''
