from html import escape as e
import re,json
BRANDS={'atlas':('BAYLEAF','THE BAY AREA CANNABIS ATLAS'),'terpenes':('NOSE NOTES','SAN JOSE TERPENE EXPLORER'),'delivery':('DOORSTEP SJ','YOUR LOCAL DELIVERY COMPANION')}
def sharing(kind):
 noun={'atlas':'shortlist','terpenes':'scent signature','delivery':'delivery plan'}[kind]
 return f'''<div class="share-controls"><button class="btn share-action" data-share="{kind}">Share my {noun}</button><button class="btn outline" data-download="{kind}">Download card</button><button class="text-button" data-copy="{kind}">Copy link</button></div><p class="share-feedback small" aria-live="polite"></p>'''
def quiz(kind):
 return '''<section class="section knowledge" id="knowledge"><div class="wrap"><div class="section-head"><div><p class="eyebrow">The 60-second knowledge check</p><h2>Would you spot the difference?</h2><p>Five quick questions. Learn something useful, then challenge a friend.</p></div></div><div class="knowledge-box" data-quiz><div class="quiz-meta"><span id="quiz-progress">Question 1 of 5</span><span id="quiz-score">0 correct</span></div><h3 id="quiz-question"></h3><div id="quiz-choices" class="quiz-choices"></div><div id="quiz-explanation" aria-live="polite"></div><button class="btn dark" id="quiz-next" hidden>Next question</button><button class="text-button" id="quiz-restart" hidden>Try again</button><button class="btn outline" data-share="quiz" id="quiz-share" hidden>Challenge a friend</button><p class="share-feedback small" aria-live="polite"></p></div></div></section>'''
def discovery(E):
 return '''<section class="section discovery" id="discovery"><div class="wrap"><div class="section-head"><div><p class="eyebrow">The discovery desk</p><h2>Build a shortlist worth sending.</h2><p>Choose a format and what you want to learn. Get a transparent starting point, then make the list your own.</p></div></div><div class="discovery-layout"><div class="discovery-input"><div class="field"><label for="discovery-format">What are you exploring?</label><select id="discovery-format"><option value="Edibles">Edibles</option><option value="Flower">Flower</option><option value="Vapes">Vapes</option><option value="Pre-rolls">Pre-rolls</option><option value="Extracts">Extracts</option><option value="Devices">Devices</option></select></div><div class="field"><label for="discovery-interest">What matters to your research?</label><select id="discovery-interest"><option value="format">Understanding the product format</option><option value="origin">The brand’s California roots</option><option value="details">Knowing what to check on the label</option></select></div><p class="small">Matches use documented formats and context, not reviews, paid placement or a quality score.</p><button class="btn dark" id="discovery-build">Build my shortlist</button></div><div class="shortlist-result" id="shortlist-panel"><p class="eyebrow">Your research shortlist</p><h3 id="shortlist-title">The edible edit.</h3><div id="shortlist-results" aria-live="polite"></div>'''+sharing('atlas')+'''<p class="small">Anyone with access to your link can open this exact selection and build their own.</p></div></div></div></section>'''
def scent(E):
 return '''<section class="scent-studio" id="scent-studio"><div class="wrap scent-layout"><div class="scent-copy"><p class="eyebrow">NOSE NOTES / YOUR SCENT SIGNATURE</p><h1>A little citrus?<br>A little forest?<br><em>Very you.</em></h1><p>Pick up to three aromas you love. Discover the compounds behind the vocabulary and make a scent card to share.</p><div class="hero-chips scent-options" aria-label="Choose up to three aroma families">'''+''.join(f'<button data-aroma="{x}" aria-pressed="false">{x}</button>' for x in ['Citrus','Pine','Floral','Earthy','Spicy','Woody','Herbal','Fresh'])+'''</div><p id="scent-limit" class="small" aria-live="polite">Aroma preferences only. Your signature does not predict cannabis effects.</p></div><div class="scent-card" id="scent-card"><div class="scent-card-top"><span>YOUR NOSE NOTES</span><span>SAN JOSE · 21+</span></div><div id="scent-symbol" class="scent-type">01 / 08</div><h2 id="scent-name">Find your signature.</h2><p id="scent-description">Choose up to three aroma families to make your own card.</p><div id="scent-tags" class="tags"></div><div id="scent-matches"></div><div class="scent-card-bottom">A little more nose. A little more you.</div></div></div><div class="wrap scent-sharing">'''+sharing('terpenes')+'''</div></section>'''
def atlas_hero():
 return '''<section class="atlas-front"><div class="wrap"><div class="edition"><span>THE SAN JOSE EDITION</span><span>BRANDS / CULTURE / BETTER QUESTIONS</span></div><div class="atlas-lead"><div><p class="eyebrow">A field guide for the curious.</p><h1>Know the name.<br><em>Find the story.</em></h1><p class="dek">Cannabis has a lot of labels. We get behind them. Explore the brands on San Jose’s shelves, compare what makes them different, and build your own shortlist.</p><form class="search" id="brand-search-form"><label class="sr-only" for="brand-search">Search brands, formats or origins</label><input id="brand-search" type="search" placeholder="A brand, a format, a place…"><button type="submit">Explore</button></form><div class="front-links"><a href="#discovery">Build your brand shortlist ↗</a><a href="guides.html">Read the field notes ↗</a></div></div><figure class="atlas-cover"><img src="assets/cannabis-macro.jpg" alt="Detail of a flowering cannabis plant"><figcaption><span>THE PLANT IS ONLY<br>PART OF THE STORY.</span><span>VOL. 01 /<br>THE BRAND EDITION</span></figcaption></figure></div></div></section>'''
def delivery_hero(E,L):
 options=''.join(f'<option value="{x["id"]}">{x["name"]}</option>' for x in E['cities'])
 return f'''<section class="delivery-dashboard"><div class="wrap dashboard-grid"><div class="delivery-heading"><p class="eyebrow">San Jose, meet your delivery companion.</p><h1>A good delivery<br>starts <em>here.</em></h1><p>The city check, the real line items, the handoff checklist. Get your plan together before opening the menu.</p><div class="delivery-local"><img src="assets/san-jose-downtown.jpg" alt="San Jose Museum of Art and downtown at night"><span>SAN JOSE &<br>THE SOUTH BAY</span></div></div><div class="dispatch-card"><div class="dispatch-heading"><span class="step-tag">01 / CHECK YOUR CITY</span><span class="dispatch-code">SJ → YOU</span></div><form class="delivery-form" id="delivery-form"><label for="city">Where are you planning a delivery?</label><div class="row"><select id="city">{options}<option value="other">Another city</option></select><button class="btn dark" type="submit">Check city</button></div><div class="city-result" id="city-result" aria-live="polite"></div></form><div class="dispatch-next"><span>02</span><div><strong>Build a clear estimate</strong><p>See the fee, tax and tip separately.</p></div><a href="#planner" aria-label="Open cost planner">↗</a></div><div class="dispatch-next"><span>03</span><div><strong>Share the plan</strong><p>Save a card. Keep your address private.</p></div><a href="#plan-sharing" aria-label="Open plan sharing">↗</a></div><p class="small">Published coverage, not a live driver map. The retailer confirms your exact address.</p></div></div></section>'''
def delivery_share():
 return '''<section class="section plan-share" id="plan-sharing"><div class="wrap"><div class="share-plan-grid"><div><p class="eyebrow">Less back-and-forth</p><h2>Your plan.<br>Ready to pass along.</h2><p>Share the city and planning total with someone helping you organize the order. No street address, payment details or ID information is included.</p>'''+sharing('delivery')+'''</div><div class="plan-ticket"><div class="ticket-top">DOORSTEP SJ <span>YOUR PLAN</span></div><h3 id="ticket-city">San Jose</h3><div id="ticket-total">$63.99</div><p id="ticket-label">Before tax</p><div id="ticket-facts"></div><p class="small">A planning snapshot. Confirm the actual order with the retailer.</p></div></div></div></section>'''
def trip_tool():
 return '''<section class="section trip-section" id="trip-tool"><div class="wrap tools-layout"><div><p class="eyebrow">Make the tradeoff visible</p><h2>What would pickup<br>cost you?</h2><p>Enter your own round-trip time and travel cost. Compare them with the published delivery fee. This is a planning comparison, not a route or arrival-time prediction.</p><a href="guide-delivery-vs-pickup.html">Read the pickup comparison guide ↗</a></div><div class="tool-panel"><div class="field-row"><div class="field"><label for="trip-minutes">Round trip, minutes</label><input id="trip-minutes" type="number" min="0" max="1440" step="1" value="30"></div><div class="field"><label for="trip-cost">Travel & parking, $</label><input id="trip-cost" type="number" min="0" max="1000" step="0.01" value="5"></div></div><div class="result" id="trip-result" aria-live="polite"></div><p class="small">Delivery still requires you to be available during the confirmed handoff window.</p></div></div></section>'''
def shelf_story():
 return '''<section class="section shelf-story"><div class="wrap"><div class="section-head"><div><p class="eyebrow">Three ways to look at a shelf</p><h2>Same category. Different questions.</h2></div></div><div class="story-columns"><a href="guide-edible-families.html"><span>01 / EDIBLES</span><h3>A gummy is a format.<br>Not a full description.</h3><p>Ingredients, amounts and product families tell the rest of the story.</p><strong>Read the edible field guide ↗</strong></a><a href="guide-device-compatibility.html"><span>02 / HARDWARE</span><h3>The right product.<br>The wrong battery?</h3><p>A short compatibility check can prevent an unnecessary purchase.</p><strong>Open the compatibility checklist ↗</strong></a><a href="guide-brand-family-tree.html"><span>03 / BRAND FAMILIES</span><h3>Different names.<br>Sometimes the same family.</h3><p>Understand the connections without treating different products as identical.</p><strong>Explore brand relationships ↗</strong></a></div></div></section>'''
def field_links(kind):
 if kind=='terpenes':
  return '''<section class="section nose-feature"><div class="wrap"><div class="nose-feature-copy"><p class="eyebrow">FROM SCENT TO SPREADSHEET</p><h2>Your nose has taste.<br>Your report has numbers.</h2><p>Use both. Convert mg/g to percent, compare the compounds you entered, and learn what a missing result really means.</p><a class="btn dark" href="lab-report-tool.html">Try the lab-report converter</a></div><div class="unit-demo"><span>THE CONVERSION TO REMEMBER</span><strong>10 <small>mg/g</small></strong><b>=</b><strong>1 <small>%</small></strong><p>Same mass fraction. Different notation.</p></div></div></section>'''
 return ''
def glossary_section(kind,X):
 return '<section class="section glossary"><div class="wrap"><div class="section-head"><div><p class="eyebrow">The useful little dictionary</p><h2>Make the jargon disappear.</h2></div></div><label class="sr-only" for="glossary-search">Search definitions</label><input id="glossary-search" type="search" placeholder="Search a word or phrase…"><div class="glossary-grid">'+''.join(f'<details data-term="{e((term+" "+desc).lower(),quote=True)}"><summary>{e(term)}</summary><p>{e(desc)}</p></details>' for term,desc in X['glossary'][kind])+'</div><p id="glossary-empty" hidden>No definitions match. Try a shorter word.</p></div></section>'
def enhance(file,body,E,L,K,X):
 if file=='index.html':
  # Replace the original shared hero with a genuinely different composition for each identity.
  end=body.find('<div class="trust">')
  if end!=-1:body=body[end:]
  hero=atlas_hero() if K=='atlas' else scent(E) if K=='terpenes' else delivery_hero(E,L)
  body=hero+body
  pos=body.find('<section class="section soft">')
  addition=discovery(E)+shelf_story() if K=='atlas' else field_links(K) if K=='terpenes' else delivery_share()+trip_tool()
  # Tools sit between the primary directory/planner and the longer editorial sections.
  if K=='delivery':
   pos=body.find('<section class="section"><div class="wrap"><div class="section-head"><div><p class="eyebrow">Around the South Bay')
  if pos<0:pos=len(body)
  body=body[:pos]+addition+body[pos:]
  body+=quiz(K)+glossary_section(K,X)
 if file.startswith('brand-'):
  id=file.removeprefix('brand-').removesuffix('.html');sections=X.get('brand_depth',{}).get(id,[])
  insert=''.join(f'<h2>{e(h)}</h2><p>{e(p)}</p>' for h,p in sections)
  insert+='<div class="article-action"><h3>Make this part of your research.</h3><button class="btn dark" data-add-shortlist="'+id+'">Add to a shareable shortlist</button><p class="share-feedback small" aria-live="polite"></p></div>'
  body=body.replace('<h2>Source & review</h2>',insert+'<h2>Source & review</h2>')
 if file.startswith('terpene-'):
  id=file.removeprefix('terpene-').removesuffix('.html');sections=X.get('terpene_depth',{}).get(id,[])
  insert=''.join(f'<h2>{e(h)}</h2><p>{e(p)}</p>' for h,p in sections)
  body=body.replace('<h2>Follow the source</h2>',insert+'<p><a class="btn dark" href="index.html#scent-studio">Build your scent signature</a></p><h2>Follow the source</h2>')
 if file.startswith('guide-'):
  id=file.removeprefix('guide-').removesuffix('.html');sections=X.get('guide_depth',{}).get(id,[])
  if sections:body=body.replace('<p class="small">Editorial review:', ''.join(f'<h2>{e(h)}</h2><p>{e(p)}</p>' for h,p in sections)+'<p class="small">Editorial review:')
 if file.startswith('delivery-'):
  id=file.removeprefix('delivery-').removesuffix('.html');sections=X.get('city_depth',{}).get(id,[])
  body=body.replace('<h2>Source</h2>', ''.join(f'<h2>{e(h)}</h2><p>{e(p)}</p>' for h,p in sections)+f'<p><a class="btn dark" href="index.html?city={id}#planner">Build a {e(next((c["name"] for c in E["cities"] if c["id"]==id),"local"))} plan</a></p><h2>Source</h2>')
 if file=='sources.html':
  refs=[('https://rawgarden.farm/lab-results/','Raw Garden: lab-result lookup'),('https://www.kivaconfections.com/about-us','Kiva: official portfolio'),('https://www.pax.com/','PAX: products and support'),('https://www.cannabis.ca.gov/licensees/cannaconnect-compliance-hub/labeling/','California Department of Cannabis Control: labeling resources')]
  extra='<h2>Further reading behind the field notes</h2><ul>'+''.join(f'<li><a href="{url}" target="_blank" rel="noopener noreferrer">{label} ↗</a></li>' for url,label in refs)+'</ul><h2>Shareable results and editorial categories</h2><p>The shortlist uses documented product formats in editorial order, with no paid ranking. Scent signatures use any-match aroma tags and reflect preferences only. Delivery cards record browser-entered assumptions. Downloaded cards are snapshots, and links reopen editable inputs using the currently published source data. Quiz answers and glossary entries are editorial learning material, reviewed with the guides.</p>'
  body=body.replace('<h2>Photography & trademarks</h2>',extra+'<h2>Photography & trademarks</h2>')
 return body
